### ISSUE TITLE
Two methods results same

### ISSUE THREAD

**Issue by lynnprosper** [shaoxiongji/fed-att#2]
Dear,
Thank you for your contribution.
I read your paper and run your code.
But I get a same test perplexity by fed-avg and your method fed-att.
All parameters are the default, and the dataset is wikitext-2.
Could you tell me whether some initiatives are wrong?

Best wishes.
2020.4.13

**Comment by shaoxiongji** [comment]
HI, try to tune epsilon, 1.2 has a lower ppl if i remember correctly.
